component ColorButton inherits Rectangle {
    in-out property text <=> txt.text;
    in-out property <brush> pressed-color: #6b8282;
    in-out property <brush> normal-color: #6c616c;
    in-out property <brush> hover-color: #456;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 2;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? pressed-color : touch.has-hover ? hover-color :  normal-color;
    height: txt.preferred-height * 1.33;
    min-width: txt.preferred-width + 20px;
    txt := Text {
        x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
        color: touch.pressed ? #fff : #eee;
    }
    touch := TouchArea { }
}

export component Recipe inherits Window {
    VerticalLayout {
        alignment: start;
        ColorButton {
            text: "Button";
        }
    }
}