import { Button, VerticalBox, StandardTableView, HorizontalBox, LineEdit, ComboBox, CheckBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 800px;
    height: 600px;
    title: "CQ版本库";
    in-out property <int> counter: 0;
    in-out property <int> current-page: 1;
    in-out property <int> total-page: 1;
    in-out property <int> current-row: 0;
    in-out property <[[StandardListViewItem]]> cqServerList: [];
    in-out property <Point> pointer;
    in-out property <string> message: "";
    callback getCqServerList();
    callback selectCqServer();
    callback parseInt(string) -> int;
    // 右键菜单
    rightMenu := PopupWindow {
        width: 200px;
        height: 200px;
        x: root.pointer.x;
        y: root.pointer.y;
        Rectangle {
            background: grey;
            width: 200px;
            height: 200px;
            VerticalBox {
                Button {
                    text: "刷新";
                }

                Button {
                    text: "下一页";
                }

                Button {
                    text: "上一页";
                }

                Button {
                    text: "复制";
                }
            }
        }
    }
    // 弹出窗口
    alertWnd := PopupWindow {
        width: 400px;
        height: 300px;
        x: parent.width / 2 - 200px;
        y: parent.height / 2 - 150px;
        Rectangle {
            background: #000000;
            width: 400px;
            height: 300px;
            VerticalBox {
                HorizontalBox {
                    Text {
                        color: #ffffff;
                        font-size: 30px;
                        horizontal-alignment: center;
                        text: root.message;
                    }
                }

                Button {
                    text: "确定";
                    height: 50px;
                    clicked => {
                        self.visible = false;
                    }
                }
            }
        }
    }

    VerticalBox {
        HorizontalLayout {
            Button {
                text: "刷新";
                clicked => {
                    root.getCqServerList();
                }
            }
        }
        StandardTableView {
            current-row-changed(e) => {
                root.current-row = e;
                root.selectCqServer();
            }
            row-pointer-event(index, event, point) => {
                if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                    root.pointer = point;
                    rightMenu.show();
                }
            }
            width: 800px;
            height: 500px;
            columns: [
                { title: "标签" },
                { title: "配套网站" },
                { title: "版本名称" },
                { title: "版本类型" },
                { title: "引擎类型" },
                { title: "更新日期" },
                { title: "游戏截图" },
                { title: "自助购买" }
            ];
            rows: root.cqServerList;
        }

        HorizontalBox {
            Text {
                text: "版本总数: \{root.counter}";
                vertical-alignment: TextVerticalAlignment.center;
            }

            Text {
                text: "当前页数: \{root.current-page}";
                vertical-alignment: TextVerticalAlignment.center;
            }

            Text {
                text: "总页数: \{root.total-page}";
                vertical-alignment: TextVerticalAlignment.center;
            }

            Button {
                text: "上一页";
                clicked => {
                    if (root.current-page == 1) {
                        root.message = "已经是第一页了";
                        alertWnd.show();
                    } else {
                        root.current-page -= 1;
                        root.getCqServerList();
                    }
                }
            }

            Button {
                text: "下一页";
                clicked => {
                    if (root.current-page == root.total-page) {
                        root.message = "已经是最后一页了";
                        alertWnd.show();
                    } else {
                        root.current-page += 1;
                        root.getCqServerList();
                    }
                }
            }

            page_num := LineEdit {
                width: 50px;
                height: 30px;
                text: "1";
            }

            Button {
                text: "跳转";
                clicked => {
                    if (root.parseInt(page_num.text) > root.total-page) {
                        root.message = "超过最大页数";
                        alertWnd.show();
                        return;
                    }
                    if (root.parseInt(page_num.text) < 1) {
                        root.message = "页数不能小于1";
                        alertWnd.show();
                        return;
                    }
                    root.current-page = parseInt(page_num.text);
                    root.getCqServerList();
                }
            }
        }
    }
}
